### ISSUE TITLE
[LUME-34] Roadmap v1.1.0

### ISSUE THREAD

**Issue by reyamir** [luminous-devs/lume#46]
**New features**

* [ ] New default image block
* [ ] Add hashtag block (newsfeed specfic note with hashtag)
* [ ] Enhancement compose
* [ ] Support long-form content (NIP-23)
* [ ] Zap
* [ ] Relay manegement
* [ ] Redesign note component

**Backlogs**

* [ ] Public channels
* [ ] Shareable space
* [ ] Backup user's spaces

<sub>From [SyncLinear.com](https://synclinear.com) | [LUME-34](https://linear.app/lume-nu/issue/LUME-34/roadmap-v110)</sub>
